#ifndef PINS_H
#define PINS_H

#include <bcm2835.h>

#define ULTRASONIC_SENSOR_TRIGGER_PIN 17
#define ULTRASONIC_SENSOR_ECHO_PIN 27
#define TRIGGER_PIN_DELAY_US 10
#define SPEED_OF_SOUND_M_US 0.343

#define SERVO_PWM_PIN 12
#define SERVO_PWM_PIN_MODE BCM2835_GPIO_FSEL_ALT0
#define SERVO_MAX_PWM 2000
#define SERVO_MIN_PWM 1000

#define ESC_PWM_PIN 13
#define ESC_PWM_PIN_MODE BCM2835_GPIO_FSEL_ALT0
#define ESC_MAX_PWM 2000
#define ESC_MIN_PWM 1000

#endif // PINS_H